app:
  mode: debug
  log: /go/src/evolution/backend/logs
  level: 3
quant:
  system:
    name: quant
    host: http://evolution-quant
    port: 8080 
    version: v1 
    prefix: evolution/quant
    cors: ["http://evolution:8888"]
    location: Asia/Shanghai
  redis:
    host: evolution-redis
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: evolution-mysql
    port: 3306
    user: root
    target: quant 
    password: 123456
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    reset: False 
    location: Asia/Shanghai
  rpc:
    host: engine
    port: 6666
time:
  system:
    name: time
    host: http://evolution-time
    port: 8080 
    version: v1 
    prefix: evolution/time
    cors: ["http://evolution:8888"]
    location: Asia/Shanghai
  redis:
    host: evolution-redis
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: evolution-mysql
    port: 3306
    user: root
    target: time
    password: 123456
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    reset: True 
    location: Asia/Shanghai
system:
  auth:
    type: "BAJwt"
    session: "auth-session"
  system:
    name: system 
    host: http://evolution-system
    port: 8080 
    version: v1 
    prefix: evolution/system
    cors: ["http://evolution:8888"]
    location: Asia/Shanghai
  redis:
    host: evolution-redis
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: evolution-mysql
    port: 3306
    user: root
    target: system 
    password: 123456
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    reset: False 
    location: Asia/Shanghai
